### ISSUE TITLE
Using the new features with ffmpeg 4.3

### ISSUE THREAD

**Issue by thaalesalves** [DanRuta/xVA-Synth#14]
Hello! I liked this new feature to tweak the output a bit. I had to use Audacity to undersample the sounds to 16 bits so I could use them with the Creation Kit, but now that we can do it directly from the app, it's even better. The problem is that it says a file missing when I try to save the file.

I download the latest version of ffmpeg from their website, but I don't know what to do with it. What am I missing here?

Thanks!

**Comment by DanRuta** [comment]
Oh, interesting. Was there an error message in an error modal?

Alternatively, can you post the last bit of text from the `server.log` file?

**Comment by thaalesalves** [comment]
I went to reproduce the error and take a screenshot, and it decided to work. I'll close the issue. Sorry for that hahaha

If the problem comes back, I'll reopen the issue with more details. Thanks!

**Comment by thaalesalves** [comment]
Alright, the error is back. Here's a screenshot.

![image](https://user-images.githubusercontent.com/2887589/106633338-80ab3580-655d-11eb-87a3-a66b351e874e.png)
![image](https://user-images.githubusercontent.com/2887589/106633381-8d2f8e00-655d-11eb-9171-d019834180ba.png)

**Comment by DanRuta** [comment]
Hmm, I've not encountered this before. And it happens on and off? Seems there's a problem with calling the python ffmpeg bindings.

Not sure if this would be the cause, but is the temporary file still at the input location when you get this?

**Comment by thaalesalves** [comment]
The temporary files are indeed disappearing without me deleting them. The play button is disabled even to files that I have already saved.
