### ISSUE TITLE
ffmpeg 4.3.2 sample overwrite error

### ISSUE THREAD

**Issue by oddlittleturtle** [DanRuta/xVA-Synth#16]
**Version:**  
CPU
1.2.2 (FO4) 

**Expected behavior:** 
samples overwrite when prompted

**Actual behavior:** 
samples do not overwrite when prompted

**Description of Unexpected Behavior:** 
Installing ffmpeg 4.3.2 after keeping samples from prior to installing ffmpeg gives error and will not overwrite previously recorded sample.

**How to reproduce error:**
- choose "Keep Sample" without installing ffmpeg 4.3.2
- install ffmpeg following instructions from video link in Description of app on NexusMods
- make minor adjustment to previous sample by clicking the edit icon
- "Generate Voice"
- error occurs

**Additional information:**
**Voice model:** Danse 1.1
**Vocoder:** WaveGlow

**Prior to installing ffmpeg:**
**Sample bit rate:** default
**Audio bit depth:** default
**Format:** wav

**After installing ffmpeg and customizing:**
**Updated bit rate:** 44100
**Updated audio bit depth:** pcm_s16le
**Format:** wav.
**Silence padding start/end:** 5 ms

**Notes:**
I've not found any documentation that this is expected behavior for the software.

I unfortunately clicked off the popup and was unable to get a screenshot of error.

I cannot find documentation for where the error logs are located to give any other info. In which folder do I look for logs in order to provide said information? The popup appears to be inefficient in this situation.

**Comment by DanRuta** [comment]
Hey there, thank you for the detailed (and very well written) report, this file overwriting issue has now been fixed in v1.2.3 :)

**Comment by oddlittleturtle** [comment]
Much appreciated. I'm happy to help and glad I was able to give you enough info to fix it. :)
I've been so busy the last few days that I've not had a chance to play around with it since then.
Have a wonderful weekend.

**Comment by oddlittleturtle** [comment]
**Follow up**
After updating to 1.2.3, I attempted to overwrite a previously made wav file and received what looked like the same error as before. This time, however, I managed to select the text from the popup. 

Same information applies as original issue (exception: voice model is Nora)

**Error message**
```
Something went wrong

Input: ./resources/app/output/temp-8846487669961398.wav
Output: C:/Games/FO4VASynth/xVASynth-win32-x64CPU/resources/app/output/fallout4/f4_nora/do you have a screw loose.wav

ffmpeg version 4.3.2-2021-02-27-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers built with gcc 10.2.0 (Rev6, Built by MSYS2 project) configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint libavutil 56. 51.100 / 56. 51.100 libavcodec 58. 91.100 / 58. 91.100 libavformat 58. 45.100 / 58. 45.100 libavdevice 58. 10.100 / 58. 10.100 libavfilter 7. 85.100 / 7. 85.100 libswscale 5. 7.100 / 5. 7.100 libswresample 3. 7.100 / 3. 7.100 libpostproc 55. 7.100 / 55. 7.100 Guessed Channel Layout for Input Stream #0.0 : mono Input #0, wav, from './resources/app/output/temp-8846487669961398.wav': Duration: 00:00:01.42, bitrate: 705 kb/s Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 22050 Hz, mono, flt, 705 kb/s Multiple -filter, -af or -vf options specified for stream 0, only the last option '-filter:a volume=.5' will be used. File 'C:/Games/FO4VASynth/xVASynth-win32-x64CPU/resources/app/output/fallout4/f4_nora/do you have a screw loose.wav' already exists. Overwrite? [y/N] Not overwriting - exiting
```

**Image of settings used:**
[Imgur](https://i.imgur.com/wdWSmdW.png)

**Current Workarounds**
- Don't use the overwrite feature.
- Copy kept recordings to a different folder, save recording into new format.

**Comment by DanRuta** [comment]
Hi,

I've made sure to delete the file first before writing, in this scenario (rather than overwriting with the correct flags). I don't think this will be an issue any more.

This will be out in v1.3.0, which is currently in beta (though the code here on github contains the fix, if you are using this).

Dan

**Comment by DanRuta** [comment]
This is now out on the Nexus websites

**Comment by oddlittleturtle** [comment]
Just checking in. As of 1.3.5, the issue appears to be resolved. :)

**Comment by DanRuta** [comment]
Nice :) I'll close this issue in that case. Thank you again for the great report, have fun!
