### ISSUE TITLE
HiFi-GAN training

### ISSUE THREAD

**Issue by longjoke** [DanRuta/xVA-Synth#21]
Are the HiFi-GAN models trained using mel-spectrograms generated from the ground truth audio, from the Tacotron2 models or  from the Fastpitch models?

**Comment by DanRuta** [comment]
currently ground truth

**Comment by longjoke** [comment]
Do you think it could be advantageous to use Tacotron2 output? Since Fastpitch is trained on that. 
It should be fairly easy to do using the extract-mels.py from Fastpitch with the --extract-mels-teacher argument.

**Comment by DanRuta** [comment]
Potentially, or even the FastPitch ones perhaps. I plan to experiment with this soon, once FastPitch gets its next update
