### ISSUE TITLE
xVASynth v3.0.0. / xVASynthVoices.json

### ISSUE THREAD

**Issue by GenesisHypno** [DanRuta/xVA-Synth#46]
xVASynthVoices.json

TypeError: model.games.forEach is not a function at file:///F:/xVASynth%20v3.0.0/resources/app/javascript/script.js:281:37 at Array.forEach () at file:///F:/xVASynth%20v3.0.0/resources/app/javascript/script.js:271:23 at Array.forEach () at file:///F:/xVASynth%20v3.0.0/resources/app/javascript/script.js:262:24 at new Promise () at window.loadAllModels (file:///F:/xVASynth%20v3.0.0/resources/app/javascript/script.js:221:12) at FSWatcher. (file:///F:/xVASynth%20v3.0.0/resources/app/javascript/script.js:1523:29) at FSWatcher.emit (node:events:526:28) at FSWatcher._handle.onchange (node:internal/fs/watchers:212:12)

**Comment by DanRuta** [comment]
It's possible that there is a badly formatted model .json file. Can this be replicated with just a single model file loaded in the app?

**Comment by GenesisHypno** [comment]
Resolved i deleted the "xVASynthVoices.json"

I found out when u set up the File Path wrong in "skyrim_fuz_ro_bork" "settings.ini" you the Error Mesages that i had. + the "xVASynthVoices.json" file
