### ISSUE TITLE
Bug: Phoneme editor container stretches longer than its content

### ISSUE THREAD

**Issue by Pendrokar** [DanRuta/xVA-Synth#51]
Users can scroll the empty part.
![image](https://github.com/DanRuta/xVA-Synth/assets/798444/c54a2234-711a-4f38-a2cd-a97019683e6b)

**Comment by DanRuta** [comment]
Yeah, this bug has been around for a few years 😄 Just added a fix for this, at long last, in 1a9a578 . Thank you for reminding me!
