### ISSUE TITLE
Issue saving files

### ISSUE THREAD

**Issue by thaalesalves** [DanRuta/xVA-Synth#6]
I'm having issues saving files recorded when there are more than two question marks in the sentence. And the phrase I'm synthesizing sounds better when I write "What? Are you mad?" than when I write these two things separately (but when I do, the file is saved normally). 

The synthesized phrase is generated and it's playable, but I can't generate any actual files with it. The issue does not occur with exclamation marks, only with question marks. Maybe dropping any punctuation contained in the sentence synthesized when generating the file name would fix this.

**Comment by DanRuta** [comment]
I've fixed this issue in the latest commit. You can patch it by replacing the script.js file, or get v1.0.3 from the Nexus, once I upload it. Thank you for raising this!
