### ISSUE TITLE
Letter tones and intensity (suggestion)

### ISSUE THREAD

**Issue by thaalesalves** [DanRuta/xVA-Synth#8]
First, I'd like to thank you for this amazing tool. Training ML models is a damn hard task, and is the very reason the development of the [Grand Prognosticator](https://github.com/thaalesalves/grand-prognosticator) has been halted for now, lmao. Kudos for this. Your tool is exactly what I needed to complete my mod, because the new lines for Falk Firebeard had no voice. Now they are perfectly voice acted, and I have you to thank you for it.

This comes as a suggestion and not an issue. I'm not versed in JavaScript, so I don't know how to help you much and I have yet to inspect the code in depth, but one interesting thing for this tool to have would be to allow the user to select more than one letter at once and raise their bars. This way, we would maintain the relative position of the bars between letters, but change their absolute position and change the tone of the sentence itself, as a whole, instead of tweaking letter by letter. I don't know how hard it would be to implement such a change, but this would surely be an interesting one!

**Comment by DanRuta** [comment]
This is an interesting suggestion. Thank you, I have added this to my list of planned features. At the moment each letter has to be adjusted individually, one-by-one, when using letter-specific settings (not the sequence-wide settings). I cannot give an ETA for when this will come live, but keep your eyes open!

Good luck with your mod, do let me know when it's public!

**Comment by thaalesalves** [comment]
Thank you for considering the suggestion! The mod is already public (it's called Domus Imperatoris, for SSE), but it has no voices for the moment. Your tool will allow me to make it sound more natural.

**Comment by thaalesalves** [comment]
@DanRuta, I won't open another issue just for asking a simple question, but it's something I'd like to ask. Do you know if there are legal implications in using a voice that was synthesized from one game in another? I wanted that Oblivion Breton voice for my Skyrim mod, but I don't know if there would be issues by doing this.

**Comment by thaalesalves** [comment]
By the way, this mod wouldn't be possible without your tool lmao

https://www.youtube.com/watch?v=FG2-PiAcaXY&lc=UgyM8IlDLS1t2tmVDQl4AaABAg

**Comment by DanRuta** [comment]
There has been no indication so far that there are any issues with using this, and I really doubt there will be. It's still relatively uncharted territory, but so long as you're not charging people for distribution of voices, you should be fine, even if something is introduced.

**Comment by thaalesalves** [comment]
Good to know. I know there wouldn't be issues using Skyrim voices in Skyrim, but Beth doesn't like it much when we use Oblivion assets in Skyrim or Morrowind, for example. But I just love the Oblivion breton voice, and I'd love to use it in my Skyrim mod.
